### ISSUE TITLE
Render documentation

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/FPSci#306]
PR #122 made some pretty big structural changes to the rendering in FPSci to support experiments that want shader modifications in the pipeline. The documentation was at a bare minimum level when we completed #122 so this issue is intended to track the need to finish up the documentation to make it easier to use.

**Comment by bboudaoud-nv** [comment]
This is my initial stab at a figure documenting the current flow of rendering, resampling, shading, and compositing in FPSci. Putting this here to foster discussion, but eventually it should probably be included in the relevant section of the `general_config.md` file:

![image](https://user-images.githubusercontent.com/48839018/116939219-fa74bd00-ac39-11eb-8369-d50b3c579ff5.png)

**Comment by jspjutNV** [comment]
I forget where we were on this, but I'm pushing this issue off to the next release.
