### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/FPSci#333]
As mentioned in #285 , there's a bunch of likely memory leaks in FPSci. It may not be super urgent to fix, but if anyone ends up playing FPSci for a long time, these leaks could cause problems for memory-constrained systems.

The variables identified so far with potential memory leaks are the following.

* `targetModels`
* `m_explosionModels`
* `materials`

**Comment by bboudaoud-nv** [comment]
A recent fix in G3D (r7188) should solve an additional memory leak that occurs when converting large arrays/tables to Any. Hopefully most of these memory leaks are now resolved.

**Comment by bboudaoud-nv** [comment]
We should come up with an approach for testing whether this is still an issue, if not we should close it.

**Comment by bboudaoud-nv** [comment]
I'm closing this issue for now, hopefully any future issues w/ memory management can be reported as more succinct and focused issues. I believe the primary leak we were hunting here was from G3D.
