### ISSUE TITLE
UI for creating new user

### ISSUE THREAD

**Issue by joohwankimNV** [NVlabs/FPSci#373]
A relatively minor request.

The steps for creating a new user is,

1. Open the dialog box (by pressing esc)
2. Type in new user name
3. Press the '+' sign next to it

Step 2 was not clear, even though there was an 'Empty!' notification message when I clicked on '+' without typing in the user name. Feels like it can be improved, although it's completely operational so not urgent at all.

**Comment by bboudaoud-nv** [comment]
The way we are currently doing this, though clever, is a bit hacky. We can probably promote the requirement for new user creation to a 1st class citizen in FPSci w/o compromising the current behavior.

I think we may want to consider adding a `requireNewUser` field to the experiment/user status configuration that indicates a new user must be provided (or an existing user can be selected if one exists). This gets more complicated if we want to add logic beyond what is currently present (i.e. requiring a new user to be entered only when certain conditions are met).

**Comment by jspjutNV** [comment]
Thinking about scenarios here. There's probably at least the following situations people might want to be able to express:

1. We know all users ahead of time, so we can pre-populate the list and we don't need an "add user" at all for an experiment.
2. We know some set of users ahead of time, but want to be able to add some users later. 
3. We don't know any of the users ahead of time, and want to require new users be added every time. This is particularly useful when sending the executable for people to run at home without bogging them down in all of the other users.
4. (alternate of 3) A pre-populated list could be provided, but restrict the startup to only one user so specialized versions can be sent to each user. Probably not ideal.

**Comment by jspjutNV** [comment]
Just to add to the connection trail, this issue is related to #365
