### ISSUE TITLE
`allSessionsCompleteFeedback` doesn't work at startup if all sessions are complete

### ISSUE THREAD

**Issue by jspjutNV** [NVlabs/FPSci#378]
I'm not sure whether I configured it wrong or if there's actually a bug here, but when I added `allSessionsCompleteFeedback = "custom message"` to my experiment config, the default message still prints on startup when I have all sessions marked as complete for the current user.

**Comment by bboudaoud-nv** [comment]
This seems like a legitimate bug, but may be challenging to fix depending on desired behavior.

The session state machine is still using a hard coded message (`"All sessions complete!"`) for the case where no session is provided, b/c in the case where all sessions are complete at startup this part of the state machine runs without a valid session configuration. If an experiment-level `allSessionsCompleteFeedback` message is provided it could be displayed, but we should test this carefully.
